name: Test All Modified Agents

on:
  push:
    branches:
      -CI/CD-test

jobs:
  detect-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read the last best agent
        id: best_agent
        run: echo "LAST_BEST_AGENT=$(cat .best_agent | awk -F '=' '{print $2}')" >> $GITHUB_ENV

      - name: Detect changed agent folders
        id: detect_agents
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'agents/')
          echo "Changed files: $CHANGED_FILES"

          CHANGED_FOLDERS=$(echo "$CHANGED_FILES" | awk -F '/' '{print $2}' | sort -u)

          if [ -z "$CHANGED_FOLDERS" ]; then
            echo "No agent changes detected, skipping..."
            exit 0
          fi

          echo "Detected agents: $CHANGED_FOLDERS"
          echo "CHANGED_FOLDERS<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FOLDERS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Give execute permissions to test.sh
        run: chmod +x task_5/test.sh

      - name: Run test.sh for each changed agent
        run: |
          for agent in $CHANGED_FOLDERS; do
            echo "Testing $agent against $LAST_BEST_AGENT"
            ./task_5/test.sh $LAST_BEST_AGENT $agent linux 20
          done
