name: Test All Agents

on:
  push:
    branches:
      - CI/CD-test
  workflow_dispatch:

jobs:
  detect-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read the last best agent
        id: best_agent
        run: echo "LAST_BEST_AGENT=$(cat ./tasks-2025/task_5/.best_agent | awk -F '=' '{print $2}')" >> $GITHUB_ENV

      - name: Detect all agent folders
        id: detect_agents
        run: |
          ALL_FOLDERS=$(ls -d agents/*/ | awk -F '/' '{print $2}')
          echo "Detected agents: $ALL_FOLDERS"
          echo "ALL_FOLDERS<<EOF" >> $GITHUB_ENV
          echo "$ALL_FOLDERS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd tasks-2025
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Give execute permissions to test.sh
        run: chmod +x task_5/test.sh

      - name: Run test.sh for each agent
        run: |
          for agent in $ALL_FOLDERS; do
            echo "Testing $agent against $LAST_BEST_AGENT"
            ./task_5/test.sh $LAST_BEST_AGENT $agent linux 20
          done
