name: Test All Agents

on:
  workflow_dispatch:

jobs:
  detect-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Best Agent and Test List
        id: set_agents
        run: |
          # Dbest agent
          echo "LAST_BEST_AGENT=base-agent" >> $GITHUB_ENV

          # agents-to-tests
          TEST_AGENTS="icbm-agent icbm-agent icbm-agent"
          echo "TEST_AGENTS=$TEST_AGENTS" >> $GITHUB_ENV

          echo "Best Agent: $LAST_BEST_AGENT"
          echo "Agents to test: $TEST_AGENTS"

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd tasks-2025
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test.sh for each agent
        run: |
          cd tasks-2025/task_5
          for agent in $TEST_AGENTS; do
            echo "Testing $agent against $LAST_BEST_AGENT"
            ./test.sh $LAST_BEST_AGENT $agent linux 20
          done
